# Generated by Django 4.2.1 on 2023-06-21 23:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_jugador_rename_escuela_club_delete_profesor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='')),
                ('celular', models.CharField(max_length=15, null=True)),
                ('telefono', models.CharField(default='', max_length=15)),
                ('egreso', models.IntegerField()),
                ('fecha_contratacion', models.DateField(verbose_name=datetime.date(2023, 6, 21))),
            ],
        ),
        migrations.AlterField(
            model_name='jugador',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Mail del jugador'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='fecha_contratacion',
            field=models.DateField(verbose_name=datetime.date(2023, 6, 21)),
        ),
    ]
